### ISSUE TITLE
How to configure listOfServers for foo-service?

### ISSUE THREAD

**Issue by octopus-prime** [Netflix/ribbon#390]
Without hyphen in service-id the configuration works well.
But with hyphen in service-id the configuration does not find the service-id.

bootstrap.yml:
```yml
foo-service:
  ribbon:
    listOfServers: http://localhost:9999
```

error:
```
Caused by: org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'foo-service.FeignClientSpecification' defined in null
```

So, how to configure listOfServers for foo-service?
